"""No-trade reasons (§17) — first-class, not an afterthought. A candidate can
have multiple simultaneous reasons; the decision engine always returns all of
them that apply, never just the first one found.
"""
from __future__ import annotations

from enum import Enum


class NoTradeReason(str, Enum):
    NO_VALID_SETUP = "NO_VALID_SETUP"
    UNCLEAR_STRUCTURE = "UNCLEAR_STRUCTURE"
    MIDDLE_OF_RANGE = "MIDDLE_OF_RANGE"
    POOR_LOCATION = "POOR_LOCATION"
    RR_BELOW_MINIMUM = "RR_BELOW_MINIMUM"
    NO_STRUCTURAL_STOP = "NO_STRUCTURAL_STOP"
    NO_VALID_TARGET = "NO_VALID_TARGET"
    VOLATILITY_TOO_LOW = "VOLATILITY_TOO_LOW"
    VOLATILITY_TOO_HIGH = "VOLATILITY_TOO_HIGH"
    VOLUME_TOO_LOW = "VOLUME_TOO_LOW"
    MULTITIMEFRAME_CONFLICT = "MULTITIMEFRAME_CONFLICT"
    EVENT_RISK = "EVENT_RISK"
    DAILY_LOSS_LIMIT_REACHED = "DAILY_LOSS_LIMIT_REACHED"
    WEEKLY_LOSS_LIMIT_REACHED = "WEEKLY_LOSS_LIMIT_REACHED"
    MAX_CONSECUTIVE_LOSSES_REACHED = "MAX_CONSECUTIVE_LOSSES_REACHED"
    PORTFOLIO_HEAT_EXCEEDED = "PORTFOLIO_HEAT_EXCEEDED"
    NET_EXPOSURE_EXCEEDED = "NET_EXPOSURE_EXCEEDED"
    LEVERAGE_LIMIT_EXCEEDED = "LEVERAGE_LIMIT_EXCEEDED"
    SYMBOL_EXPOSURE_EXCEEDED = "SYMBOL_EXPOSURE_EXCEEDED"
    INSUFFICIENT_BUYING_POWER = "INSUFFICIENT_BUYING_POWER"
    RISK_BUDGET_EXCEEDED = "RISK_BUDGET_EXCEEDED"
    DAILY_REALIZED_LOSS_LIMIT_REACHED = "DAILY_REALIZED_LOSS_LIMIT_REACHED"
    OPEN_RISK_DATA_INCOMPLETE = "OPEN_RISK_DATA_INCOMPLETE"
    MAX_POSITIONS_REACHED = "MAX_POSITIONS_REACHED"
    MAX_TRADES_REACHED = "MAX_TRADES_REACHED"
    DATA_QUALITY_FAILURE = "DATA_QUALITY_FAILURE"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    INVALID_ACCOUNT_STATE = "INVALID_ACCOUNT_STATE"
    INVALID_RISK_POLICY = "INVALID_RISK_POLICY"
    INVALID_NUMERIC_INPUT = "INVALID_NUMERIC_INPUT"
